runMode: create-baseline
projectFolders: [test-docs, insurance-policy-docs]
baselineDir: golden-copy
includeDocs:
  - project: insurance-policy-docs
    doc: Acme Inc - Private Car Stand Alone Own Damage Add-On Cover.pdf
  - project: insurance-policy-docs
    doc: Acme Inc - Health Plus Policy.pdf
  - project: insurance-policy-docs    
    doc: Acme Inc - Burglary Insurance Policy (Commercial) Add-On Covers.pdf
  - project: test-docs
    doc: Test-Acme Inc - Private Car Stand Alone Own Damage Add-On Cover.pdf
excludeDocs:
  - project: insurance-policy-docs
    doc: Acme Inc - Private Car Stand Alone Own Damage Add-On Cover.pdf
specialDocConfigs:
  - project: insurance-policy-docs
    doc: Acme Inc - Private Car Stand Alone Own Damage Add-On Cover.pdf
    includePages: []
    excludePages: [4, 7]
  - project: insurance-policy-docs
    doc: Acme Inc - Health Plus Policy.pdf
    includePages: [2, 4]
    excludePages: []
  - project: insurance-policy-docs
    doc: Acme Inc - Burglary Insurance Policy (Commercial) Add-On Covers.pdf
    includePages: []
    excludePages: [2]
createNewBuildPerDoc: true
percyConfigs:
  waitForTimeout: 200